name: CI

on:
  push:
    branches: [ release-1.14 ]
  pull_request:
    branches: [ release-1.14 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up Kind
      uses: engineerd/setup-kind@v0.5.0
      with:
        skipClusterCreation: true 

    - name:
      run:
         DOCKER_RUN_OPTIONS="-e HUB=localhost:5000 -e TAG=istio-testing" ./prow/integ-suite-kind.sh test.integration.pilot.kube
